<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IntermediateOutputPath>..\..\output\obj\yay_see_sharp.domain\$(Configuration)\</IntermediateOutputPath>
  </PropertyGroup>

</Project>
