namespace yay_see_sharp.infrastructure.Resources;

internal static class LocalizationResources
{
    public const string English = "en";
    public const string Slovak = "sk";

    public static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Strings =
        new Dictionary<string, IReadOnlyDictionary<string, string>>
        {
            [English] = new Dictionary<string, string>
            {
                ["Navigation.Dashboard"] = "Dashboard",
                ["Navigation.Search"] = "Search",
                ["Navigation.Installed"] = "Installed",
                ["Navigation.Settings"] = "Settings",

                ["Backend.ModeReal"] = "Real",
                ["Backend.ModeDemo"] = "Demo",
                ["Backend.ModeUnavailable"] = "yay missing",
                ["Theme.System"] = "System",
                ["Theme.Light"] = "Light",
                ["Theme.Dark"] = "Dark",
                ["Dashboard.UnsupportedWarning"] = "Real yay backend is limited to Arch Linux and CachyOS; using realistic Demo mode for {0}.",
                ["Dashboard.YayMissingWarning"] = "yay was not found on PATH. Using realistic Demo mode until it's installed.",

                ["Dashboard.Refresh"] = "Refresh",
                ["Dashboard.Welcome"] = "Welcome back",
                ["Dashboard.LastSynced"] = "Last synced {0} ago",
                ["Dashboard.LastSyncedNever"] = "Not synced yet",
                ["Dashboard.ScheduledUpdatesFound"] = "{0} update(s) found by the scheduled check",
                ["Dashboard.Relative.Moments"] = "moments",
                ["Dashboard.Relative.Minute"] = "minute",
                ["Dashboard.Relative.Minutes"] = "minutes",
                ["Dashboard.Relative.Hour"] = "hour",
                ["Dashboard.Relative.Hours"] = "hours",
                ["Dashboard.Relative.Day"] = "day",
                ["Dashboard.Relative.Days"] = "days",
                ["Dashboard.Statistics"] = "Statistics",
                ["Dashboard.Updates"] = "Updates",
                ["Dashboard.Installed"] = "Installed",
                ["Dashboard.Explicit"] = "Explicit",
                ["Dashboard.Dependencies"] = "Dependencies",
                ["Dashboard.Aur"] = "AUR",
                ["Dashboard.UpdatesAvailable"] = "Updates available",
                ["Dashboard.Orphans"] = "Orphans",
                ["Dashboard.NoUpdates"] = "No updates available.",
                ["Dashboard.UpdateAll"] = "Update all",
                ["Dashboard.UpdatePackage"] = "Update",

                ["Installed.Empty"] = "No packages installed.",

                ["Search.Placeholder"] = "Search packages…",
                ["Search.Button"] = "Search",
                ["Search.NoResults"] = "No packages found.",
                ["Search.SourceAll"] = "All",
                ["Search.SourceOfficial"] = "Official",
                ["Search.SourceAur"] = "AUR",

                ["Package.Install"] = "Install",
                ["Package.Uninstall"] = "Uninstall",
                ["Package.Homepage"] = "Homepage",
                ["Package.NoDetails"] = "No details available.",
                ["Package.StateInstalled"] = "Installed",
                ["Package.StateNotInstalled"] = "Not installed",
                ["Package.StateUpdateAvailable"] = "Update available",

                ["Operation.Cancel"] = "Cancel",
                ["Operation.Stage.Preparing"] = "Preparing",
                ["Operation.Stage.ResolvingDependencies"] = "Resolving dependencies",
                ["Operation.Stage.Downloading"] = "Downloading",
                ["Operation.Stage.Applying"] = "Applying",
                ["Operation.Stage.Verifying"] = "Verifying",
                ["Operation.Stage.Completed"] = "Completed",
                ["Operation.Stage.Failed"] = "Failed",
                ["Operation.Stage.Cancelled"] = "Cancelled",

                ["Settings.Appearance"] = "Appearance",
                ["Settings.Language"] = "Language",
                ["Settings.Language.Hint"] = "Slovenčina supported today · more community languages arriving soon",
                ["Settings.Theme"] = "Theme",
                ["Settings.CloseAction"] = "Close action",
                ["Settings.Notifications"] = "Desktop notifications",
                ["Settings.Notifications.Hint"] = "On install, update and error",
                ["Settings.RemoveOrphans"] = "Remove orphan dependencies",
                ["Settings.UpdateScheduleTime"] = "Daily update check time",
                ["Settings.AutoUpdate"] = "Check for updates automatically",
                ["Settings.AutoUpdate.HintDaily"] = "Daily check at {0}",
                ["Settings.MinimizeToTray"] = "Minimize to tray on close",
                ["Settings.Engine"] = "Package manager engine",
                ["Settings.Engine.Hint"] = "Detected on this system",
                ["Settings.Engine.Yay"] = "yay",
                ["Settings.Engine.Paru"] = "paru",
                ["Settings.Detect"] = "Detect",
                ["Settings.DetectResultTitle"] = "Detection result",
                ["Settings.DetectFoundYay"] = "Found yay on PATH — it is already the active engine.",
                ["Settings.DetectFoundParu"] = "Found paru on PATH. Only yay is supported for now, so nothing changed.",
                ["Settings.DetectFoundNone"] = "No supported package manager engine found on PATH.",
                ["Settings.SimulatedModeTitle"] = "Simulated mode",
                ["Settings.SimulatedModeDetect"] = "The app is running in simulated mode. Real detection is not available.",
                ["Settings.SimulatedModeYay"] = "In simulated mode at least one package manager engine must be active. Install yay on Arch Linux for real mode.",
                ["Settings.AurHelper"] = "AUR helper",
                ["Settings.BuildDirectory"] = "Build directory",
                ["Settings.Browse"] = "Browse…",
                ["Settings.Save"] = "Save",
                ["Settings.Saved"] = "Saved",
                ["Settings.CloseAction.HideToTray"] = "Hide to tray",
                ["Settings.CloseAction.Exit"] = "Exit",
                ["Settings.Language.En"] = "English",
                ["Settings.Language.Sk"] = "Slovak",

                ["FolderBrowser.Title"] = "Select build directory",
                ["FolderBrowser.Cancel"] = "Cancel",
                ["FolderBrowser.Select"] = "Select folder",

                ["AuthPrompt.Title"] = "Authentication required",
                ["AuthPrompt.Body"] = "Yay See Sharp needs your password to install and update packages as root.",
                ["AuthPrompt.Password"] = "Password",
                ["AuthPrompt.Cancel"] = "Cancel",
                ["AuthPrompt.Authenticate"] = "Authenticate",

                ["BackendInstall.Title"] = "yay is not installed",
                ["BackendInstall.Body"] = "yay was not found on PATH. Install it now to switch from Demo mode to managing real packages on this system?",
                ["BackendInstall.Confirm"] = "Install yay",
                ["BackendInstall.Close"] = "Close",
                ["BackendInstall.RestartHint"] = "yay was installed. Restart Yay See Sharp to switch to Real mode.",

                ["Build.Title"] = "Building {0}",
                ["Build.RunInBackground"] = "Run in background",

                ["Loading.Status"] = "Syncing AUR metadata…",

                ["Package.ViewPkgbuild"] = "View PKGBUILD",
                ["Package.Maintainer"] = "Maintainer",
                ["Package.Votes"] = "Votes",
                ["Package.InstallSize"] = "Install size",
                ["Package.Dependencies"] = "Dependencies",

                ["Pkgbuild.Title"] = "PKGBUILD — {0}",
                ["Pkgbuild.Close"] = "Close",
                ["Pkgbuild.FetchFailed"] = "Failed to fetch PKGBUILD ({0})",

                ["Tray.Restore"] = "Restore",
                ["Tray.Exit"] = "Exit",

                ["Notification.UpdatesAvailable"] = "Updates are available.",
                ["Notification.InstallSucceeded"] = "Package installed successfully.",
                ["Notification.UninstallSucceeded"] = "Package uninstalled successfully.",
                ["Notification.UpdateCompleted"] = "Update completed.",
                ["Notification.OperationFailed"] = "Operation failed.",
                ["Notification.SudoRenewed"] = "Sudo authorization renewed.",

                ["Generic.ErrorPrefix"] = "Error",
            },
            [Slovak] = new Dictionary<string, string>
            {
                ["Navigation.Dashboard"] = "Prehľad",
                ["Navigation.Search"] = "Hľadať",
                ["Navigation.Installed"] = "Nainštalované",
                ["Navigation.Settings"] = "Nastavenia",

                ["Backend.ModeReal"] = "Reálny",
                ["Backend.ModeDemo"] = "Demo",
                ["Backend.ModeUnavailable"] = "yay chýba",
                ["Theme.System"] = "Systémová",
                ["Theme.Light"] = "Svetlá",
                ["Theme.Dark"] = "Tmavá",
                ["Dashboard.UnsupportedWarning"] = "Reálny yay backend je obmedzený na Arch Linux a CachyOS; pre {0} sa používa realistický Demo režim.",
                ["Dashboard.YayMissingWarning"] = "yay sa nenašiel na PATH. Kým sa nenainštaluje, používa sa realistický Demo režim.",

                ["Dashboard.Refresh"] = "Obnoviť",
                ["Dashboard.Welcome"] = "Vitajte späť",
                ["Dashboard.LastSynced"] = "Naposledy synchronizované pred {0}",
                ["Dashboard.LastSyncedNever"] = "Zatiaľ nesynchronizované",
                ["Dashboard.ScheduledUpdatesFound"] = "Naplánovaná kontrola našla {0} aktualizácií",
                ["Dashboard.Relative.Moments"] = "chvíľou",
                ["Dashboard.Relative.Minute"] = "minútou",
                ["Dashboard.Relative.Minutes"] = "minútami",
                ["Dashboard.Relative.Hour"] = "hodinou",
                ["Dashboard.Relative.Hours"] = "hodinami",
                ["Dashboard.Relative.Day"] = "dňom",
                ["Dashboard.Relative.Days"] = "dňami",
                ["Dashboard.Statistics"] = "Štatistiky",
                ["Dashboard.Updates"] = "Aktualizácie",
                ["Dashboard.Installed"] = "Nainštalované",
                ["Dashboard.Explicit"] = "Explicitné",
                ["Dashboard.Dependencies"] = "Závislosti",
                ["Dashboard.Aur"] = "AUR",
                ["Dashboard.UpdatesAvailable"] = "Dostupné aktualizácie",
                ["Dashboard.Orphans"] = "Osirotené",
                ["Dashboard.NoUpdates"] = "Žiadne dostupné aktualizácie.",
                ["Dashboard.UpdateAll"] = "Aktualizovať všetko",
                ["Dashboard.UpdatePackage"] = "Aktualizovať",

                ["Installed.Empty"] = "Žiadne nainštalované balíky.",

                ["Search.Placeholder"] = "Hľadať balíky…",
                ["Search.Button"] = "Hľadať",
                ["Search.NoResults"] = "Neboli nájdené žiadne balíky.",
                ["Search.SourceAll"] = "Všetky",
                ["Search.SourceOfficial"] = "Oficiálne",
                ["Search.SourceAur"] = "AUR",

                ["Package.Install"] = "Inštalovať",
                ["Package.Uninstall"] = "Odinštalovať",
                ["Package.Homepage"] = "Domovská stránka",
                ["Package.NoDetails"] = "Žiadne dostupné detaily.",
                ["Package.StateInstalled"] = "Nainštalované",
                ["Package.StateNotInstalled"] = "Nenainštalované",
                ["Package.StateUpdateAvailable"] = "Dostupná aktualizácia",

                ["Operation.Cancel"] = "Zrušiť",
                ["Operation.Stage.Preparing"] = "Príprava",
                ["Operation.Stage.ResolvingDependencies"] = "Riešenie závislostí",
                ["Operation.Stage.Downloading"] = "Sťahovanie",
                ["Operation.Stage.Applying"] = "Aplikovanie",
                ["Operation.Stage.Verifying"] = "Overovanie",
                ["Operation.Stage.Completed"] = "Dokončené",
                ["Operation.Stage.Failed"] = "Zlyhalo",
                ["Operation.Stage.Cancelled"] = "Zrušené",

                ["Settings.Appearance"] = "Vzhľad",
                ["Settings.Language"] = "Jazyk",
                ["Settings.Language.Hint"] = "Slovenčina je dnes podporovaná · ďalšie jazyky komunity čoskoro",
                ["Settings.Theme"] = "Téma",
                ["Settings.CloseAction"] = "Akcia pri zatvorení",
                ["Settings.Notifications"] = "Notifikácie na pracovnej ploche",
                ["Settings.Notifications.Hint"] = "Pri inštalácii, aktualizácii a chybe",
                ["Settings.RemoveOrphans"] = "Odstrániť osirotené závislosti",
                ["Settings.UpdateScheduleTime"] = "Čas dennej kontroly aktualizácií",
                ["Settings.AutoUpdate"] = "Automaticky kontrolovať aktualizácie",
                ["Settings.AutoUpdate.HintDaily"] = "Denná kontrola o {0}",
                ["Settings.MinimizeToTray"] = "Pri zatvorení skryť do systémovej lišty",
                ["Settings.Engine"] = "Nástroj správcu balíkov",
                ["Settings.Engine.Hint"] = "Zistené na tomto systéme",
                ["Settings.Engine.Yay"] = "yay",
                ["Settings.Engine.Paru"] = "paru",
                ["Settings.Detect"] = "Zistiť",
                ["Settings.DetectResultTitle"] = "Výsledok detekcie",
                ["Settings.DetectFoundYay"] = "Našiel som yay v PATH — už je aktívnym engine.",
                ["Settings.DetectFoundParu"] = "Našiel som paru v PATH. Zatiaľ je podporovaný len yay, takže nič sa nezmenilo.",
                ["Settings.DetectFoundNone"] = "Na PATH som nenašiel žiadny podporovaný package manager engine.",
                ["Settings.SimulatedModeTitle"] = "Simulovaný mód",
                ["Settings.SimulatedModeDetect"] = "Aplikácia beží v simulovanom móde. Reálna detekcia nie je dostupná.",
                ["Settings.SimulatedModeYay"] = "V simulovanom móde musí byť aktívny aspoň jeden package manager engine. Nainštaluj yay na Arch Linux pre reálny mód.",
                ["Settings.AurHelper"] = "AUR pomocník",
                ["Settings.BuildDirectory"] = "Priečinok pre zostavenie",
                ["Settings.Browse"] = "Prehľadávať…",
                ["Settings.Save"] = "Uložiť",
                ["Settings.Saved"] = "Uložené",
                ["Settings.CloseAction.HideToTray"] = "Skryť do systémovej lišty",
                ["Settings.CloseAction.Exit"] = "Ukončiť",
                ["Settings.Language.En"] = "Angličtina",
                ["Settings.Language.Sk"] = "Slovenčina",

                ["FolderBrowser.Title"] = "Vybrať priečinok pre zostavenie",
                ["FolderBrowser.Cancel"] = "Zrušiť",
                ["FolderBrowser.Select"] = "Vybrať priečinok",

                ["AuthPrompt.Title"] = "Vyžaduje sa overenie",
                ["AuthPrompt.Body"] = "Yay See Sharp potrebuje vaše heslo na inštaláciu a aktualizáciu balíkov ako root.",
                ["AuthPrompt.Password"] = "Heslo",
                ["AuthPrompt.Cancel"] = "Zrušiť",
                ["AuthPrompt.Authenticate"] = "Overiť",

                ["BackendInstall.Title"] = "yay nie je nainštalovaný",
                ["BackendInstall.Body"] = "yay sa nenašiel na PATH. Nainštalovať ho teraz a prepnúť z Demo režimu na správu reálnych balíkov na tomto systéme?",
                ["BackendInstall.Confirm"] = "Nainštalovať yay",
                ["BackendInstall.Close"] = "Zavrieť",
                ["BackendInstall.RestartHint"] = "yay bol nainštalovaný. Reštartujte Yay See Sharp na prepnutie do Reálneho režimu.",

                ["Build.Title"] = "Zostavuje sa {0}",
                ["Build.RunInBackground"] = "Spustiť na pozadí",

                ["Loading.Status"] = "Synchronizácia metadát AUR…",

                ["Package.ViewPkgbuild"] = "Zobraziť PKGBUILD",
                ["Package.Maintainer"] = "Správca",
                ["Package.Votes"] = "Hlasy",
                ["Package.InstallSize"] = "Veľkosť inštalácie",
                ["Package.Dependencies"] = "Závislosti",

                ["Pkgbuild.Title"] = "PKGBUILD — {0}",
                ["Pkgbuild.Close"] = "Zavrieť",
                ["Pkgbuild.FetchFailed"] = "Nepodarilo sa načítať PKGBUILD ({0})",

                ["Tray.Restore"] = "Obnoviť",
                ["Tray.Exit"] = "Ukončiť",

                ["Notification.UpdatesAvailable"] = "Sú dostupné aktualizácie.",
                ["Notification.InstallSucceeded"] = "Balík bol úspešne nainštalovaný.",
                ["Notification.UninstallSucceeded"] = "Balík bol úspešne odinštalovaný.",
                ["Notification.UpdateCompleted"] = "Aktualizácia dokončená.",
                ["Notification.OperationFailed"] = "Operácia zlyhala.",
                ["Notification.SudoRenewed"] = "Sudo oprávnenie bolo obnovené.",

                ["Generic.ErrorPrefix"] = "Chyba",
            },
        };
}
