namespace yay_see_sharp.infrastructure.Resources;

internal static class LocalizationResources
{
    public const string English = "en";
    public const string Slovak = "sk";
    public const string German = "de";
    public const string Polish = "pl";

    public static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Strings =
        new Dictionary<string, IReadOnlyDictionary<string, string>>
        {
            [English] = new Dictionary<string, string>
            {
                ["Navigation.Dashboard"] = "Dashboard",
                ["Navigation.Search"] = "Search",
                ["Navigation.Installed"] = "Installed",
                ["Navigation.Settings"] = "Settings",

                ["Backend.ModeReal"] = "Real",
                ["Backend.ModeDemo"] = "Demo",
                ["Backend.ModeUnavailable"] = "yay missing",
                ["Theme.System"] = "System",
                ["Theme.Light"] = "Light",
                ["Theme.Dark"] = "Dark",
                ["Dashboard.UnsupportedWarning"] = "Real yay backend is limited to Arch Linux and CachyOS; using realistic Demo mode for {0}.",
                ["Dashboard.YayMissingWarning"] = "yay was not found on PATH. Using realistic Demo mode until it's installed.",

                ["Dashboard.Refresh"] = "Refresh",
                ["Dashboard.Welcome"] = "Welcome back",
                ["Dashboard.LastSynced"] = "Last synced {0} ago",
                ["Dashboard.LastSyncedNever"] = "Not synced yet",
                ["Dashboard.ScheduledUpdatesFound"] = "{0} update(s) found by the scheduled check",
                ["Dashboard.Relative.Moments"] = "moments",
                ["Dashboard.Relative.Minute"] = "minute",
                ["Dashboard.Relative.Minutes"] = "minutes",
                ["Dashboard.Relative.Hour"] = "hour",
                ["Dashboard.Relative.Hours"] = "hours",
                ["Dashboard.Relative.Day"] = "day",
                ["Dashboard.Relative.Days"] = "days",
                ["Dashboard.Statistics"] = "Statistics",
                ["Dashboard.Updates"] = "Updates",
                ["Dashboard.Installed"] = "Installed",
                ["Dashboard.Explicit"] = "Explicit",
                ["Dashboard.Dependencies"] = "Dependencies",
                ["Dashboard.Aur"] = "AUR",
                ["Dashboard.UpdatesAvailable"] = "Updates available",
                ["Dashboard.Orphans"] = "Orphans",
                ["Dashboard.NoUpdates"] = "No updates available.",
                ["Dashboard.UpdateAll"] = "Update all",
                ["Dashboard.UpdatePackage"] = "Update",

                ["Installed.Empty"] = "No packages installed.",

                ["Search.Placeholder"] = "Search packages…",
                ["Search.Button"] = "Search",
                ["Search.NoResults"] = "No packages found.",
                ["Search.SourceAll"] = "All",
                ["Search.SourceOfficial"] = "Official",
                ["Search.SourceAur"] = "AUR",

                ["Package.Install"] = "Install",
                ["Package.Uninstall"] = "Uninstall",
                ["Package.Homepage"] = "Homepage",
                ["Package.NoDetails"] = "No details available.",
                ["Package.StateInstalled"] = "Installed",
                ["Package.StateNotInstalled"] = "Not installed",
                ["Package.StateUpdateAvailable"] = "Update available",

                ["Operation.Cancel"] = "Cancel",
                ["Operation.Stage.Preparing"] = "Preparing",
                ["Operation.Stage.ResolvingDependencies"] = "Resolving dependencies",
                ["Operation.Stage.Downloading"] = "Downloading",
                ["Operation.Stage.Applying"] = "Applying",
                ["Operation.Stage.Verifying"] = "Verifying",
                ["Operation.Stage.Completed"] = "Completed",
                ["Operation.Stage.Failed"] = "Failed",
                ["Operation.Stage.Cancelled"] = "Cancelled",

                ["Settings.Appearance"] = "Appearance",
                ["Settings.Language"] = "Language",
                ["Settings.Language.Hint"] = "English, Slovenčina, Deutsch and Polski supported",
                ["Settings.Theme"] = "Theme",
                ["Settings.CloseAction"] = "Close action",
                ["Settings.Notifications"] = "Desktop notifications",
                ["Settings.Notifications.Hint"] = "On install, update and error",
                ["Settings.RemoveOrphans"] = "Remove orphan dependencies",
                ["Settings.UpdateScheduleTime"] = "Daily update check time",
                ["Settings.AutoUpdate"] = "Check for updates automatically",
                ["Settings.AutoUpdate.HintDaily"] = "Daily check at {0}",
                ["Settings.MinimizeToTray"] = "Minimize to tray on close",
                ["Settings.Engine"] = "Package manager engine",
                ["Settings.Engine.Hint"] = "Detected on this system",
                ["Settings.Engine.Yay"] = "yay",
                ["Settings.Engine.Paru"] = "paru",
                ["Settings.Detect"] = "Detect",
                ["Settings.DetectResultTitle"] = "Detection result",
                ["Settings.DetectFoundYay"] = "Found yay on PATH — it is already the active engine.",
                ["Settings.DetectFoundParu"] = "Found paru on PATH. Only yay is supported for now, so nothing changed.",
                ["Settings.DetectFoundNone"] = "No supported package manager engine found on PATH.",
                ["Settings.SimulatedModeTitle"] = "Simulated mode",
                ["Settings.SimulatedModeDetect"] = "The app is running in simulated mode. Real detection is not available.",
                ["Settings.SimulatedModeYay"] = "In simulated mode at least one package manager engine must be active. Install yay on Arch Linux for real mode.",
                ["Settings.AurHelper"] = "AUR helper",
                ["Settings.BuildDirectory"] = "Build directory",
                ["Settings.Browse"] = "Browse…",
                ["Settings.Save"] = "Save",
                ["Settings.Saved"] = "Saved",
                ["Settings.CloseAction.HideToTray"] = "Hide to tray",
                ["Settings.CloseAction.Exit"] = "Exit",
                ["Settings.Language.En"] = "English",
                ["Settings.Language.Sk"] = "Slovak",
                ["Settings.Language.De"] = "German",
                ["Settings.Language.Pl"] = "Polish",

                ["FolderBrowser.Title"] = "Select build directory",
                ["FolderBrowser.Cancel"] = "Cancel",
                ["FolderBrowser.Select"] = "Select folder",

                ["AuthPrompt.Title"] = "Authentication required",
                ["AuthPrompt.Body"] = "Yay See Sharp needs your password to install and update packages as root.",
                ["AuthPrompt.Password"] = "Password",
                ["AuthPrompt.Cancel"] = "Cancel",
                ["AuthPrompt.Authenticate"] = "Authenticate",

                ["BackendInstall.Title"] = "yay is not installed",
                ["BackendInstall.Body"] = "yay was not found on PATH. Install it now to switch from Demo mode to managing real packages on this system?",
                ["BackendInstall.Confirm"] = "Install yay",
                ["BackendInstall.Close"] = "Close",
                ["BackendInstall.RestartHint"] = "yay was installed. Restart Yay See Sharp to switch to Real mode.",

                ["Build.Title"] = "Building {0}",
                ["Build.RunInBackground"] = "Run in background",

                ["Loading.Status"] = "Syncing AUR metadata…",

                ["Package.ViewPkgbuild"] = "View PKGBUILD",
                ["Package.Maintainer"] = "Maintainer",
                ["Package.Votes"] = "Votes",
                ["Package.InstallSize"] = "Install size",
                ["Package.Dependencies"] = "Dependencies",

                ["Pkgbuild.Title"] = "PKGBUILD — {0}",
                ["Pkgbuild.Close"] = "Close",
                ["Pkgbuild.FetchFailed"] = "Failed to fetch PKGBUILD ({0})",

                ["Tray.Restore"] = "Restore",
                ["Tray.Exit"] = "Exit",

                ["Notification.UpdatesAvailable"] = "Updates are available.",
                ["Notification.InstallSucceeded"] = "Package installed successfully.",
                ["Notification.UninstallSucceeded"] = "Package uninstalled successfully.",
                ["Notification.UpdateCompleted"] = "Update completed.",
                ["Notification.OperationFailed"] = "Operation failed.",
                ["Notification.SudoRenewed"] = "Sudo authorization renewed.",

                ["Generic.ErrorPrefix"] = "Error",
            },
            [Slovak] = new Dictionary<string, string>
            {
                ["Navigation.Dashboard"] = "Prehľad",
                ["Navigation.Search"] = "Hľadať",
                ["Navigation.Installed"] = "Nainštalované",
                ["Navigation.Settings"] = "Nastavenia",

                ["Backend.ModeReal"] = "Reálny",
                ["Backend.ModeDemo"] = "Demo",
                ["Backend.ModeUnavailable"] = "yay chýba",
                ["Theme.System"] = "Systémová",
                ["Theme.Light"] = "Svetlá",
                ["Theme.Dark"] = "Tmavá",
                ["Dashboard.UnsupportedWarning"] = "Reálny yay backend je obmedzený na Arch Linux a CachyOS; pre {0} sa používa realistický Demo režim.",
                ["Dashboard.YayMissingWarning"] = "yay sa nenašiel na PATH. Kým sa nenainštaluje, používa sa realistický Demo režim.",

                ["Dashboard.Refresh"] = "Obnoviť",
                ["Dashboard.Welcome"] = "Vitajte späť",
                ["Dashboard.LastSynced"] = "Naposledy synchronizované pred {0}",
                ["Dashboard.LastSyncedNever"] = "Zatiaľ nesynchronizované",
                ["Dashboard.ScheduledUpdatesFound"] = "Naplánovaná kontrola našla {0} aktualizácií",
                ["Dashboard.Relative.Moments"] = "chvíľou",
                ["Dashboard.Relative.Minute"] = "minútou",
                ["Dashboard.Relative.Minutes"] = "minútami",
                ["Dashboard.Relative.Hour"] = "hodinou",
                ["Dashboard.Relative.Hours"] = "hodinami",
                ["Dashboard.Relative.Day"] = "dňom",
                ["Dashboard.Relative.Days"] = "dňami",
                ["Dashboard.Statistics"] = "Štatistiky",
                ["Dashboard.Updates"] = "Aktualizácie",
                ["Dashboard.Installed"] = "Nainštalované",
                ["Dashboard.Explicit"] = "Explicitné",
                ["Dashboard.Dependencies"] = "Závislosti",
                ["Dashboard.Aur"] = "AUR",
                ["Dashboard.UpdatesAvailable"] = "Dostupné aktualizácie",
                ["Dashboard.Orphans"] = "Osirotené",
                ["Dashboard.NoUpdates"] = "Žiadne dostupné aktualizácie.",
                ["Dashboard.UpdateAll"] = "Aktualizovať všetko",
                ["Dashboard.UpdatePackage"] = "Aktualizovať",

                ["Installed.Empty"] = "Žiadne nainštalované balíky.",

                ["Search.Placeholder"] = "Hľadať balíky…",
                ["Search.Button"] = "Hľadať",
                ["Search.NoResults"] = "Neboli nájdené žiadne balíky.",
                ["Search.SourceAll"] = "Všetky",
                ["Search.SourceOfficial"] = "Oficiálne",
                ["Search.SourceAur"] = "AUR",

                ["Package.Install"] = "Inštalovať",
                ["Package.Uninstall"] = "Odinštalovať",
                ["Package.Homepage"] = "Domovská stránka",
                ["Package.NoDetails"] = "Žiadne dostupné detaily.",
                ["Package.StateInstalled"] = "Nainštalované",
                ["Package.StateNotInstalled"] = "Nenainštalované",
                ["Package.StateUpdateAvailable"] = "Dostupná aktualizácia",

                ["Operation.Cancel"] = "Zrušiť",
                ["Operation.Stage.Preparing"] = "Príprava",
                ["Operation.Stage.ResolvingDependencies"] = "Riešenie závislostí",
                ["Operation.Stage.Downloading"] = "Sťahovanie",
                ["Operation.Stage.Applying"] = "Aplikovanie",
                ["Operation.Stage.Verifying"] = "Overovanie",
                ["Operation.Stage.Completed"] = "Dokončené",
                ["Operation.Stage.Failed"] = "Zlyhalo",
                ["Operation.Stage.Cancelled"] = "Zrušené",

                ["Settings.Appearance"] = "Vzhľad",
                ["Settings.Language"] = "Jazyk",
                ["Settings.Language.Hint"] = "Podporovaná je angličtina, slovenčina, nemčina a poľština",
                ["Settings.Theme"] = "Téma",
                ["Settings.CloseAction"] = "Akcia pri zatvorení",
                ["Settings.Notifications"] = "Notifikácie na pracovnej ploche",
                ["Settings.Notifications.Hint"] = "Pri inštalácii, aktualizácii a chybe",
                ["Settings.RemoveOrphans"] = "Odstrániť osirotené závislosti",
                ["Settings.UpdateScheduleTime"] = "Čas dennej kontroly aktualizácií",
                ["Settings.AutoUpdate"] = "Automaticky kontrolovať aktualizácie",
                ["Settings.AutoUpdate.HintDaily"] = "Denná kontrola o {0}",
                ["Settings.MinimizeToTray"] = "Pri zatvorení skryť do systémovej lišty",
                ["Settings.Engine"] = "Nástroj správcu balíkov",
                ["Settings.Engine.Hint"] = "Zistené na tomto systéme",
                ["Settings.Engine.Yay"] = "yay",
                ["Settings.Engine.Paru"] = "paru",
                ["Settings.Detect"] = "Zistiť",
                ["Settings.DetectResultTitle"] = "Výsledok detekcie",
                ["Settings.DetectFoundYay"] = "Našiel som yay v PATH — už je aktívnym engine.",
                ["Settings.DetectFoundParu"] = "Našiel som paru v PATH. Zatiaľ je podporovaný len yay, takže nič sa nezmenilo.",
                ["Settings.DetectFoundNone"] = "Na PATH som nenašiel žiadny podporovaný package manager engine.",
                ["Settings.SimulatedModeTitle"] = "Simulovaný mód",
                ["Settings.SimulatedModeDetect"] = "Aplikácia beží v simulovanom móde. Reálna detekcia nie je dostupná.",
                ["Settings.SimulatedModeYay"] = "V simulovanom móde musí byť aktívny aspoň jeden package manager engine. Nainštaluj yay na Arch Linux pre reálny mód.",
                ["Settings.AurHelper"] = "AUR pomocník",
                ["Settings.BuildDirectory"] = "Priečinok pre zostavenie",
                ["Settings.Browse"] = "Prehľadávať…",
                ["Settings.Save"] = "Uložiť",
                ["Settings.Saved"] = "Uložené",
                ["Settings.CloseAction.HideToTray"] = "Skryť do systémovej lišty",
                ["Settings.CloseAction.Exit"] = "Ukončiť",
                ["Settings.Language.En"] = "Angličtina",
                ["Settings.Language.Sk"] = "Slovenčina",
                ["Settings.Language.De"] = "Nemčina",
                ["Settings.Language.Pl"] = "Poľština",

                ["FolderBrowser.Title"] = "Vybrať priečinok pre zostavenie",
                ["FolderBrowser.Cancel"] = "Zrušiť",
                ["FolderBrowser.Select"] = "Vybrať priečinok",

                ["AuthPrompt.Title"] = "Vyžaduje sa overenie",
                ["AuthPrompt.Body"] = "Yay See Sharp potrebuje vaše heslo na inštaláciu a aktualizáciu balíkov ako root.",
                ["AuthPrompt.Password"] = "Heslo",
                ["AuthPrompt.Cancel"] = "Zrušiť",
                ["AuthPrompt.Authenticate"] = "Overiť",

                ["BackendInstall.Title"] = "yay nie je nainštalovaný",
                ["BackendInstall.Body"] = "yay sa nenašiel na PATH. Nainštalovať ho teraz a prepnúť z Demo režimu na správu reálnych balíkov na tomto systéme?",
                ["BackendInstall.Confirm"] = "Nainštalovať yay",
                ["BackendInstall.Close"] = "Zavrieť",
                ["BackendInstall.RestartHint"] = "yay bol nainštalovaný. Reštartujte Yay See Sharp na prepnutie do Reálneho režimu.",

                ["Build.Title"] = "Zostavuje sa {0}",
                ["Build.RunInBackground"] = "Spustiť na pozadí",

                ["Loading.Status"] = "Synchronizácia metadát AUR…",

                ["Package.ViewPkgbuild"] = "Zobraziť PKGBUILD",
                ["Package.Maintainer"] = "Správca",
                ["Package.Votes"] = "Hlasy",
                ["Package.InstallSize"] = "Veľkosť inštalácie",
                ["Package.Dependencies"] = "Závislosti",

                ["Pkgbuild.Title"] = "PKGBUILD — {0}",
                ["Pkgbuild.Close"] = "Zavrieť",
                ["Pkgbuild.FetchFailed"] = "Nepodarilo sa načítať PKGBUILD ({0})",

                ["Tray.Restore"] = "Obnoviť",
                ["Tray.Exit"] = "Ukončiť",

                ["Notification.UpdatesAvailable"] = "Sú dostupné aktualizácie.",
                ["Notification.InstallSucceeded"] = "Balík bol úspešne nainštalovaný.",
                ["Notification.UninstallSucceeded"] = "Balík bol úspešne odinštalovaný.",
                ["Notification.UpdateCompleted"] = "Aktualizácia dokončená.",
                ["Notification.OperationFailed"] = "Operácia zlyhala.",
                ["Notification.SudoRenewed"] = "Sudo oprávnenie bolo obnovené.",

                ["Generic.ErrorPrefix"] = "Chyba",
            },
            [German] = new Dictionary<string, string>
            {
                ["Navigation.Dashboard"] = "Übersicht",
                ["Navigation.Search"] = "Suchen",
                ["Navigation.Installed"] = "Installiert",
                ["Navigation.Settings"] = "Einstellungen",

                ["Backend.ModeReal"] = "Echt",
                ["Backend.ModeDemo"] = "Demo",
                ["Backend.ModeUnavailable"] = "yay fehlt",
                ["Theme.System"] = "System",
                ["Theme.Light"] = "Hell",
                ["Theme.Dark"] = "Dunkel",
                ["Dashboard.UnsupportedWarning"] = "Der echte yay-Backend ist auf Arch Linux und CachyOS beschränkt; für {0} wird der realistische Demo-Modus verwendet.",
                ["Dashboard.YayMissingWarning"] = "yay wurde nicht im PATH gefunden. Bis zur Installation wird der realistische Demo-Modus verwendet.",

                ["Dashboard.Refresh"] = "Aktualisieren",
                ["Dashboard.Welcome"] = "Willkommen zurück",
                ["Dashboard.LastSynced"] = "Zuletzt synchronisiert vor {0}",
                ["Dashboard.LastSyncedNever"] = "Noch nicht synchronisiert",
                ["Dashboard.ScheduledUpdatesFound"] = "Die geplante Prüfung hat {0} Update(s) gefunden",
                ["Dashboard.Relative.Moments"] = "einem Moment",
                ["Dashboard.Relative.Minute"] = "Minute",
                ["Dashboard.Relative.Minutes"] = "Minuten",
                ["Dashboard.Relative.Hour"] = "Stunde",
                ["Dashboard.Relative.Hours"] = "Stunden",
                ["Dashboard.Relative.Day"] = "Tag",
                ["Dashboard.Relative.Days"] = "Tagen",
                ["Dashboard.Statistics"] = "Statistiken",
                ["Dashboard.Updates"] = "Updates",
                ["Dashboard.Installed"] = "Installiert",
                ["Dashboard.Explicit"] = "Explizit",
                ["Dashboard.Dependencies"] = "Abhängigkeiten",
                ["Dashboard.Aur"] = "AUR",
                ["Dashboard.UpdatesAvailable"] = "Updates verfügbar",
                ["Dashboard.Orphans"] = "Verwaiste",
                ["Dashboard.NoUpdates"] = "Keine Updates verfügbar.",
                ["Dashboard.UpdateAll"] = "Alle aktualisieren",
                ["Dashboard.UpdatePackage"] = "Aktualisieren",

                ["Installed.Empty"] = "Keine Pakete installiert.",

                ["Search.Placeholder"] = "Pakete suchen…",
                ["Search.Button"] = "Suchen",
                ["Search.NoResults"] = "Keine Pakete gefunden.",
                ["Search.SourceAll"] = "Alle",
                ["Search.SourceOfficial"] = "Offiziell",
                ["Search.SourceAur"] = "AUR",

                ["Package.Install"] = "Installieren",
                ["Package.Uninstall"] = "Deinstallieren",
                ["Package.Homepage"] = "Projektseite",
                ["Package.NoDetails"] = "Keine Details verfügbar.",
                ["Package.StateInstalled"] = "Installiert",
                ["Package.StateNotInstalled"] = "Nicht installiert",
                ["Package.StateUpdateAvailable"] = "Update verfügbar",

                ["Operation.Cancel"] = "Abbrechen",
                ["Operation.Stage.Preparing"] = "Vorbereiten",
                ["Operation.Stage.ResolvingDependencies"] = "Abhängigkeiten auflösen",
                ["Operation.Stage.Downloading"] = "Herunterladen",
                ["Operation.Stage.Applying"] = "Anwenden",
                ["Operation.Stage.Verifying"] = "Prüfen",
                ["Operation.Stage.Completed"] = "Abgeschlossen",
                ["Operation.Stage.Failed"] = "Fehlgeschlagen",
                ["Operation.Stage.Cancelled"] = "Abgebrochen",

                ["Settings.Appearance"] = "Darstellung",
                ["Settings.Language"] = "Sprache",
                ["Settings.Language.Hint"] = "English, Slovenčina, Deutsch und Polski werden unterstützt",
                ["Settings.Theme"] = "Design",
                ["Settings.CloseAction"] = "Aktion beim Schließen",
                ["Settings.Notifications"] = "Desktop-Benachrichtigungen",
                ["Settings.Notifications.Hint"] = "Bei Installation, Update und Fehlern",
                ["Settings.RemoveOrphans"] = "Verwaiste Abhängigkeiten entfernen",
                ["Settings.UpdateScheduleTime"] = "Zeit der täglichen Update-Prüfung",
                ["Settings.AutoUpdate"] = "Automatisch nach Updates suchen",
                ["Settings.AutoUpdate.HintDaily"] = "Tägliche Prüfung um {0}",
                ["Settings.MinimizeToTray"] = "Beim Schließen in die Taskleiste minimieren",
                ["Settings.Engine"] = "Paketmanager-Engine",
                ["Settings.Engine.Hint"] = "Auf diesem System erkannt",
                ["Settings.Engine.Yay"] = "yay",
                ["Settings.Engine.Paru"] = "paru",
                ["Settings.Detect"] = "Erkennen",
                ["Settings.DetectResultTitle"] = "Erkennungsergebnis",
                ["Settings.DetectFoundYay"] = "yay im PATH gefunden — es ist bereits die aktive Engine.",
                ["Settings.DetectFoundParu"] = "paru im PATH gefunden. Derzeit wird nur yay unterstützt, daher wurde nichts geändert.",
                ["Settings.DetectFoundNone"] = "Keine unterstützte Paketmanager-Engine im PATH gefunden.",
                ["Settings.SimulatedModeTitle"] = "Simulierter Modus",
                ["Settings.SimulatedModeDetect"] = "Die App läuft im simulierten Modus. Echte Erkennung ist nicht verfügbar.",
                ["Settings.SimulatedModeYay"] = "Im simulierten Modus muss mindestens eine Paketmanager-Engine aktiv sein. Installiere yay auf Arch Linux für den echten Modus.",
                ["Settings.AurHelper"] = "AUR-Helfer",
                ["Settings.BuildDirectory"] = "Build-Verzeichnis",
                ["Settings.Browse"] = "Durchsuchen…",
                ["Settings.Save"] = "Speichern",
                ["Settings.Saved"] = "Gespeichert",
                ["Settings.CloseAction.HideToTray"] = "In den Tray ausblenden",
                ["Settings.CloseAction.Exit"] = "Beenden",
                ["Settings.Language.En"] = "Englisch",
                ["Settings.Language.Sk"] = "Slowakisch",
                ["Settings.Language.De"] = "Deutsch",
                ["Settings.Language.Pl"] = "Polnisch",

                ["FolderBrowser.Title"] = "Build-Verzeichnis auswählen",
                ["FolderBrowser.Cancel"] = "Abbrechen",
                ["FolderBrowser.Select"] = "Ordner auswählen",

                ["AuthPrompt.Title"] = "Authentifizierung erforderlich",
                ["AuthPrompt.Body"] = "Yay See Sharp benötigt Ihr Passwort, um Pakete als root zu installieren und zu aktualisieren.",
                ["AuthPrompt.Password"] = "Passwort",
                ["AuthPrompt.Cancel"] = "Abbrechen",
                ["AuthPrompt.Authenticate"] = "Authentifizieren",

                ["BackendInstall.Title"] = "yay ist nicht installiert",
                ["BackendInstall.Body"] = "yay wurde nicht im PATH gefunden. Jetzt installieren, um vom Demo-Modus zur Verwaltung echter Pakete auf diesem System zu wechseln?",
                ["BackendInstall.Confirm"] = "yay installieren",
                ["BackendInstall.Close"] = "Schließen",
                ["BackendInstall.RestartHint"] = "yay wurde installiert. Starten Sie Yay See Sharp neu, um in den echten Modus zu wechseln.",

                ["Build.Title"] = "{0} wird erstellt",
                ["Build.RunInBackground"] = "Im Hintergrund ausführen",

                ["Loading.Status"] = "AUR-Metadaten werden synchronisiert…",

                ["Package.ViewPkgbuild"] = "PKGBUILD anzeigen",
                ["Package.Maintainer"] = "Betreuer",
                ["Package.Votes"] = "Stimmen",
                ["Package.InstallSize"] = "Installationsgröße",
                ["Package.Dependencies"] = "Abhängigkeiten",

                ["Pkgbuild.Title"] = "PKGBUILD — {0}",
                ["Pkgbuild.Close"] = "Schließen",
                ["Pkgbuild.FetchFailed"] = "PKGBUILD konnte nicht abgerufen werden ({0})",

                ["Tray.Restore"] = "Wiederherstellen",
                ["Tray.Exit"] = "Beenden",

                ["Notification.UpdatesAvailable"] = "Updates sind verfügbar.",
                ["Notification.InstallSucceeded"] = "Paket erfolgreich installiert.",
                ["Notification.UninstallSucceeded"] = "Paket erfolgreich deinstalliert.",
                ["Notification.UpdateCompleted"] = "Update abgeschlossen.",
                ["Notification.OperationFailed"] = "Vorgang fehlgeschlagen.",
                ["Notification.SudoRenewed"] = "Sudo-Berechtigung erneuert.",

                ["Generic.ErrorPrefix"] = "Fehler",
            },
            [Polish] = new Dictionary<string, string>
            {
                ["Navigation.Dashboard"] = "Pulpit",
                ["Navigation.Search"] = "Szukaj",
                ["Navigation.Installed"] = "Zainstalowane",
                ["Navigation.Settings"] = "Ustawienia",

                ["Backend.ModeReal"] = "Rzeczywisty",
                ["Backend.ModeDemo"] = "Demo",
                ["Backend.ModeUnavailable"] = "brak yay",
                ["Theme.System"] = "Systemowy",
                ["Theme.Light"] = "Jasny",
                ["Theme.Dark"] = "Ciemny",
                ["Dashboard.UnsupportedWarning"] = "Prawdziwy backend yay jest ograniczony do Arch Linux i CachyOS; dla {0} używany jest realistyczny tryb Demo.",
                ["Dashboard.YayMissingWarning"] = "Nie znaleziono yay w PATH. Do czasu instalacji używany jest realistyczny tryb Demo.",

                ["Dashboard.Refresh"] = "Odśwież",
                ["Dashboard.Welcome"] = "Witaj ponownie",
                ["Dashboard.LastSynced"] = "Ostatnia synchronizacja {0} temu",
                ["Dashboard.LastSyncedNever"] = "Jeszcze nie zsynchronizowano",
                ["Dashboard.ScheduledUpdatesFound"] = "Zaplanowana kontrola znalazła {0} aktualizacji",
                ["Dashboard.Relative.Moments"] = "chwilę",
                ["Dashboard.Relative.Minute"] = "minutę",
                ["Dashboard.Relative.Minutes"] = "minut",
                ["Dashboard.Relative.Hour"] = "godzinę",
                ["Dashboard.Relative.Hours"] = "godzin",
                ["Dashboard.Relative.Day"] = "dzień",
                ["Dashboard.Relative.Days"] = "dni",
                ["Dashboard.Statistics"] = "Statystyki",
                ["Dashboard.Updates"] = "Aktualizacje",
                ["Dashboard.Installed"] = "Zainstalowane",
                ["Dashboard.Explicit"] = "Jawne",
                ["Dashboard.Dependencies"] = "Zależności",
                ["Dashboard.Aur"] = "AUR",
                ["Dashboard.UpdatesAvailable"] = "Dostępne aktualizacje",
                ["Dashboard.Orphans"] = "Osierocone",
                ["Dashboard.NoUpdates"] = "Brak dostępnych aktualizacji.",
                ["Dashboard.UpdateAll"] = "Aktualizuj wszystko",
                ["Dashboard.UpdatePackage"] = "Aktualizuj",

                ["Installed.Empty"] = "Nie zainstalowano żadnych pakietów.",

                ["Search.Placeholder"] = "Szukaj pakietów…",
                ["Search.Button"] = "Szukaj",
                ["Search.NoResults"] = "Nie znaleziono pakietów.",
                ["Search.SourceAll"] = "Wszystkie",
                ["Search.SourceOfficial"] = "Oficjalne",
                ["Search.SourceAur"] = "AUR",

                ["Package.Install"] = "Zainstaluj",
                ["Package.Uninstall"] = "Odinstaluj",
                ["Package.Homepage"] = "Strona domowa",
                ["Package.NoDetails"] = "Brak dostępnych szczegółów.",
                ["Package.StateInstalled"] = "Zainstalowano",
                ["Package.StateNotInstalled"] = "Niezainstalowano",
                ["Package.StateUpdateAvailable"] = "Dostępna aktualizacja",

                ["Operation.Cancel"] = "Anuluj",
                ["Operation.Stage.Preparing"] = "Przygotowywanie",
                ["Operation.Stage.ResolvingDependencies"] = "Rozwiązywanie zależności",
                ["Operation.Stage.Downloading"] = "Pobieranie",
                ["Operation.Stage.Applying"] = "Stosowanie",
                ["Operation.Stage.Verifying"] = "Weryfikowanie",
                ["Operation.Stage.Completed"] = "Ukończono",
                ["Operation.Stage.Failed"] = "Niepowodzenie",
                ["Operation.Stage.Cancelled"] = "Anulowano",

                ["Settings.Appearance"] = "Wygląd",
                ["Settings.Language"] = "Język",
                ["Settings.Language.Hint"] = "Obsługiwane są języki English, Slovenčina, Deutsch i Polski",
                ["Settings.Theme"] = "Motyw",
                ["Settings.CloseAction"] = "Akcja przy zamknięciu",
                ["Settings.Notifications"] = "Powiadomienia pulpitu",
                ["Settings.Notifications.Hint"] = "Przy instalacji, aktualizacji i błędach",
                ["Settings.RemoveOrphans"] = "Usuń osierocone zależności",
                ["Settings.UpdateScheduleTime"] = "Godzina codziennej kontroli aktualizacji",
                ["Settings.AutoUpdate"] = "Automatycznie sprawdzaj aktualizacje",
                ["Settings.AutoUpdate.HintDaily"] = "Codzienna kontrola o {0}",
                ["Settings.MinimizeToTray"] = "Minimalizuj do zasobnika przy zamknięciu",
                ["Settings.Engine"] = "Silnik menedżera pakietów",
                ["Settings.Engine.Hint"] = "Wykryto na tym systemie",
                ["Settings.Engine.Yay"] = "yay",
                ["Settings.Engine.Paru"] = "paru",
                ["Settings.Detect"] = "Wykryj",
                ["Settings.DetectResultTitle"] = "Wynik wykrywania",
                ["Settings.DetectFoundYay"] = "Znaleziono yay w PATH — jest już aktywnym silnikiem.",
                ["Settings.DetectFoundParu"] = "Znaleziono paru w PATH. Na razie obsługiwany jest tylko yay, więc nic się nie zmieniło.",
                ["Settings.DetectFoundNone"] = "Nie znaleziono obsługiwanego silnika menedżera pakietów w PATH.",
                ["Settings.SimulatedModeTitle"] = "Tryb symulowany",
                ["Settings.SimulatedModeDetect"] = "Aplikacja działa w trybie symulowanym. Prawdziwe wykrywanie nie jest dostępne.",
                ["Settings.SimulatedModeYay"] = "W trybie symulowanym musi być aktywny co najmniej jeden silnik menedżera pakietów. Zainstaluj yay na Arch Linux, aby uzyskać tryb rzeczywisty.",
                ["Settings.AurHelper"] = "Pomocnik AUR",
                ["Settings.BuildDirectory"] = "Katalog budowania",
                ["Settings.Browse"] = "Przeglądaj…",
                ["Settings.Save"] = "Zapisz",
                ["Settings.Saved"] = "Zapisano",
                ["Settings.CloseAction.HideToTray"] = "Ukryj w zasobniku",
                ["Settings.CloseAction.Exit"] = "Zakończ",
                ["Settings.Language.En"] = "Angielski",
                ["Settings.Language.Sk"] = "Słowacki",
                ["Settings.Language.De"] = "Niemiecki",
                ["Settings.Language.Pl"] = "Polski",

                ["FolderBrowser.Title"] = "Wybierz katalog budowania",
                ["FolderBrowser.Cancel"] = "Anuluj",
                ["FolderBrowser.Select"] = "Wybierz folder",

                ["AuthPrompt.Title"] = "Wymagane uwierzytelnienie",
                ["AuthPrompt.Body"] = "Yay See Sharp potrzebuje Twojego hasła, aby instalować i aktualizować pakiety jako root.",
                ["AuthPrompt.Password"] = "Hasło",
                ["AuthPrompt.Cancel"] = "Anuluj",
                ["AuthPrompt.Authenticate"] = "Uwierzytelnij",

                ["BackendInstall.Title"] = "yay nie jest zainstalowany",
                ["BackendInstall.Body"] = "Nie znaleziono yay w PATH. Zainstalować go teraz, aby przejść z trybu Demo do zarządzania prawdziwymi pakietami na tym systemie?",
                ["BackendInstall.Confirm"] = "Zainstaluj yay",
                ["BackendInstall.Close"] = "Zamknij",
                ["BackendInstall.RestartHint"] = "yay został zainstalowany. Uruchom ponownie Yay See Sharp, aby przełączyć się na tryb rzeczywisty.",

                ["Build.Title"] = "Budowanie {0}",
                ["Build.RunInBackground"] = "Uruchom w tle",

                ["Loading.Status"] = "Synchronizowanie metadanych AUR…",

                ["Package.ViewPkgbuild"] = "Pokaż PKGBUILD",
                ["Package.Maintainer"] = "Opiekun",
                ["Package.Votes"] = "Głosy",
                ["Package.InstallSize"] = "Rozmiar instalacji",
                ["Package.Dependencies"] = "Zależności",

                ["Pkgbuild.Title"] = "PKGBUILD — {0}",
                ["Pkgbuild.Close"] = "Zamknij",
                ["Pkgbuild.FetchFailed"] = "Nie udało się pobrać PKGBUILD ({0})",

                ["Tray.Restore"] = "Przywróć",
                ["Tray.Exit"] = "Zakończ",

                ["Notification.UpdatesAvailable"] = "Dostępne są aktualizacje.",
                ["Notification.InstallSucceeded"] = "Pakiet został pomyślnie zainstalowany.",
                ["Notification.UninstallSucceeded"] = "Pakiet został pomyślnie odinstalowany.",
                ["Notification.UpdateCompleted"] = "Aktualizacja zakończona.",
                ["Notification.OperationFailed"] = "Operacja nie powiodła się.",
                ["Notification.SudoRenewed"] = "Odnowiono uprawnienia sudo.",

                ["Generic.ErrorPrefix"] = "Błąd",
            },
        };
}
